#!/bin/bash

OUTPUT_DIR="haskell_output_14812908410984127"
stack ghc -- -O2 $1.hs -outputdir $OUTPUT_DIR
rm -rf $OUTPUT_DIR
printf "script generated\nrunning script...\n\n"
time $1
printf "\nscript complete\ndeleting script...\n"
rm $1
echo "done"
